apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf-1
spec:
  config: '{
            "cniVersion": "0.3.1",
            "type": "macvlan",
            "master": "ens1f1",
            "mode": "bridge",
            "ipam": {
                "type": "host-local",
                "ranges": [
                    [ {
                         "subnet": "192.168.20.0/24",
                         "rangeStart": "192.168.20.198",
                         "rangeEnd": "192.168.20.200",
                         "gateway": "192.168.20.1"
                    } ]
                ]
            }
        }'
