apiVersion: v1
kind: Service
metadata:
  name: multus-service
  annotations:
    "loxilb.io/multus-nets" : '["mac-vlan1", "mac-vlan2"]'
spec:
  externalTrafficPolicy: Local
  loadBalancerClass: loxilb.io/loxilb
  selector:
    app: pod-case-01
  ports:
    - port: 55002
      targetPort: 5002
  type: LoadBalancer
